title: Study Less конспект лекцій
description: "Збірник конспектів, навчальних матеріалів та посилань на презентації для студентів курсу Study Less."
annotation: "Ваш кишеньковий помічник у навчанні: уся необхідна інформація з вебінарів в одному місці."
